---
artifactory_baseurl: "https://artifactory.pyrsoftware.ca/artifactory"
artifactory_releases_folder: "packagesraw"
artifactory_username: anonymous
artifactory_password: password
get_url_force_basic_auth: false

casinoserver_bin_branch: "TAG/AUX2401"
coreserver_bin_branch: "TAG/2401E"

loki_url: https://services.loki.distributor.casino.iss-test.starsops.com/loki/api/v1/push
region: eu-west-1
service_start_mode: "auto"
service_state: "started"

handsarchive_dbm_instance: 11