---
# Restart monitoring service
- name: Restart hesender Monitoring service
  ansible.windows.win_service:
    name: PYR_HESENDER
    state: restarted

- name: Restart memsender Monitoring service
  ansible.windows.win_service:
    name: PYR_MEMSENDER
    state: restarted

- name: Restart AUXUKGW service
  ansible.windows.win_service:
    name: PYR_C_AUXUKGW
    state: restarted
  when: molecule_yml is undefined and 'launch' not in ansible_skip_tags

- name: Restart promtail
  ansible.windows.win_service:
    name: Promtail
    state: restarted

- name: Restart telegraf
  ansible.windows.win_service:
    name: telegraf
    state: restarted
