---
namespace: casino
name: server
version: 1.0.0
readme: README.md
authors:
  - Alice Kaerast <alice_kaerast@flutterint.com>
description: Configures Casino servers and installs applications
tags:
  - linux
  - windows
  - applications
dependencies: {}
repository: https://github.com/flutterint/ansible-casino-server-collection
build_ignore: []
