---
namespace: casino
name: server
version: 1.0.0
readme: README.md
authors:
  - QuyDacVuong
description: Configures Casino servers and installs applications
tags:
  - linux
  - windows
  - applications
dependencies: {}
repository: https://github.com/QuyDacVuong/ansible-collection.git
build_ignore: []
