---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: promtail
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-amazonlinux2}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  host_vars:
    stationname: "TEST"
    lobby_host: "127.0.10.136"
    hercules_host: "127.0.10.145"
    web_dispatcher_host: "127.0.10.135"
    advertise_host: "127.0.10.133"
  inventory:
    group_vars:
      all:
        tags:
          CasinoEnvironment: unittest
          Name: cipwa
          Platform: Linux
          Zone: zone1
        instance_id: i-abc123
