---
- name: Converge
  hosts: sbgintegration
  become: true

  pre_tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - acl
          - tar
          - openssl
          - unzip
        state: present
    - name: Create bigdisk0 directory
      ansible.builtin.file:
        path: /bigdisk0
        state: directory
        mode: "0755"
    - name: Create telegraf group
      ansible.builtin.group:
        name: telegraf
        state: present
    - name: Create telegraf user
      ansible.builtin.user:
        name: telegraf
        group: telegraf
        state: present
    - name: Create telegraf config directory
      ansible.builtin.file:
        path: /etc/telegraf/telegraf.d
        state: directory
        mode: "0755"
  roles:
    - role: casino.server.sbgintegration
