---
- name: Reload docker
  ansible.builtin.service:
    name: docker
    state: reloaded
- name: Restart telegraf
  ansible.builtin.systemd_service:
    name: telegraf
    state: restarted
  when: molecule_yml is undefined
