---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: molecule_yml is undefined

- name: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
  when: molecule_yml is undefined

- name: Reload telegraf
  ansible.builtin.service:
    name: telegraf
    state: reloaded
  when: molecule_yml is undefined
