---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gateway
    image: "ghcr.io/alicekaerast/docker-${MOLECULE_DISTRO:-amazonlinux2023}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /run
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        region: eu-west-1
        instance_id: i-1234
        tags:
          Zone: zone1
          CasinoEnvironment: unittest
          Name: gateway
          Platform: Linux
        stationname: "TEST"
        advertise_host: "127.0.10.133"
