---
- name: Converge
  hosts: tomcat
  become: true

  pre_tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name:
          - acl
          - tar
        state: present
    - name: Create bigdisk0 directory
      ansible.builtin.file:
        path: /bigdisk0
        state: directory
        mode: "0755"
  roles:
    - role: java
    - role: tomcat
