---
# Restart monitoring service
- name: Restart hesender Monitoring service
  ansible.windows.win_service:
    name: PYR_HESENDER
    state: restarted

- name: Restart memsender Monitoring service
  ansible.windows.win_service:
    name: PYR_MEMSENDER
    state: restarted

- name: Restart ip2country service
  ansible.windows.win_service:
    name: PYR_C_IP2COUNTRY
    state: restarted
  when: "'launch' not in ansible_skip_tags"

- name: Restart Telegraf
  ansible.windows.win_service:
    name: Telegraf
    state: restarted
